---
title: "pstat274_hw06_aoxu"
author: "AO XU"
date: "2022-11-07"
output: html_document
---

### Problem 1

Solution:

$\rho_w(1)=-0.04 \pm1.96*0.08 = (-0.1968,0.1168)$

$\rho_w(2)=-0.5 \pm1.96*0.1 = (-0.696,-0.304)$

$\rho_w(3)=0.03 \pm1.96*0.11 = (-0.1856,0.2456)$

$\rho_w(4)=-0.01 \pm1.96*0.11 = (-0.2256,0.2056)$

$\rho_w(5)=0.01 \pm1.96*0.11 = (-0.2056,0.2256)$

$\rho_w(6)=0.02 \pm1.96*0.11 = (-0.1956,0.2356)$

$\rho_w(7)=0.03 \pm1.96*0.11 = (-0.1856,0.2456)$

$\rho_w(8)=-0.01 \pm1.96*0.11 = (-0.2256,0.2056)$

All intervals include 0 except $\rho_w(2)$, so it's MA(2) model.

$\phi_z(B) Z_{t}=\theta_z(B)W_t$, $\phi_z(B)=1$, $\theta_z(B)=1+\theta_{z_1}B\theta_{z_2}B^2=1+\theta_{z_2}B^2$

$\phi_z(B)\phi(B)X_t=\theta(B)\theta_z(B)W_t$ $\Longrightarrow$ $(1-B\phi_1)X_t=(1+\theta_1B)(1+\theta_zB^2)W_t=(1+\theta_1B+\theta_zB^2+\theta_1 \theta_z B^3)W_t$ 

Therefore, it's ARMA(1,3) model.

### Problem 2

$H_0: \mu=0$ vs $H_1: \mu \neq 0$

$\bar{X}$~$N(\mu,{\sigma_x^2 \over100})$ $\Longrightarrow$ ${\bar{X}-\mu}\over \sqrt{var(\bar{X})\over100}$~$N(0,1)$

$P(-1.96 \leq {\bar{X}-\mu \over \sqrt{var(\bar{X})\over100}}\leq1.96) = 0.95$
$\Longrightarrow$ $-1.96\sqrt{var(\bar{X})\over100} \leq {0.271-\mu}\leq1.96\sqrt{var(\bar{X})\over100}$ $\Longrightarrow$ $0.271-1.96\sqrt{var(\bar{X})\over100} \leq {\mu}\leq 0.271+1.96\sqrt{var(\bar{X})\over100}$

Since it's AR(1) model. we could get that $var(\bar{x}) \approx \gamma_x(0)+2 \sum\limits_{n=1}^{\infty} \gamma_x(h)=\gamma_x(0)+2 \sum\limits_{n=1}^{\infty} \phi^h\gamma_x(0)$=$\gamma_x(0)(1+2 \sum\limits_{n=1}^{\infty} \phi*\phi^{n-1})$ = $\sigma^2 \over 1-\phi^2$ $(1+2 {\phi\over 1- \phi})$ = $2 \over 1 -0.6^2$$(1+2*{0.6\over1-0.6})$=12.5

Therefore, we could get that $0.271-1.96\sqrt{12.5\over100} \leq {\mu}\leq 0.271+1.96\sqrt{12.5\over100}$ $\Longrightarrow$ $-0.422 \leq \mu \leq0.964$. 

Since $\mu=0$ is in the 95% confidence interval (-0.422,0.964), we could get that null hypothesis $\mu=0$ cannot be rejected.

### G1

Solution:

(a) By using ACF: $\hat\rho$ ~ $N(\rho(h),h^{-1})$, $\hat\rho(h) \pm {1.96 \over \sqrt{n}},n=200$.

$\rho(1)=0.427 \pm {1.96 \over \sqrt{200}}=(0.2884,0.5655)$

Since it doesn't contain 0 and $\rho(1) \neq 0$, so we get that $\{ X_t - \mu \}$ is not a white noise.

(b) AR(2)

$\hat\mu = \bar{x} = 3.82$

Since $\rho(1)= \phi(1)+\phi(2)\rho(1)$ and $\rho(2) = \phi(1)\rho(1)+\phi(2)$，

we could get that $\phi(1) = {\rho(1) -\rho(1) \rho(2) \over 1-\rho(1)^2}$ = 0.274
and $\phi(2) = \rho(2) - {\rho(1)^2 -\rho(1)^2 \rho(2) \over 1-\rho(1)^2}$ = 0.358

$\gamma(0) = \phi_1\gamma(1) + \phi_2 \gamma(2) + \sigma_Z^2$

$\Longrightarrow$ $\sigma_z^2 = \gamma(0)(1-\phi_1\rho(1)-\phi_2\rho(2)) = 0.82$

(c) AR(2) model

$\alpha(2) = \phi_2 =0.358$

$\alpha(1) = {\phi_1 \over1-\phi_2}=0.427$

$\alpha(k) = 0$ for $k \neq 1,2$



