---
title: "pstat271_lab05_aoxu"
author: "AO XU"
date: "2022-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tsdl)
milk <- subset(tsdl, 12, "Agriculture")[[3]]
plot(milk)
```

```{r}
# To make it more stationary, we use the following code:
dmilk <- diff(milk, 12)
ddmilk <- diff(dmilk, 1)
```

a.

It has a positive linear trend and seasonality, then it is not stationary.

b.

```{r}
dmilk <- diff(milk, 12)
ddmilk <- diff(dmilk, 1)
acf(ddmilk, lag.max = 50, main="")
pacf(ddmilk,lag.max = 50, main="")
```
c. 

Since it's one seasonal differencing, then we get that D=1 at lag s=12. And ddmilk applied one differencing to remove trend, so d=1. From acf, there is one peak at 1, so Q is 1. From PACF, there are peaks at 1,2 or 4. So P could be 1 or 2 or 4. For 0-1 from both ACF and PACF, there are no peaks. Then we get 

SARIMA (0, 1, 0) x (1, 1, 1$)_{s=12}$

SARIMA (0, 1, 0) x (2, 1, 1$)_{s=12}$

SARIMA (0, 1, 0) x (4, 1, 1$)_{s=12}$

d.

```{r}
library(astsa)
#library(sarima)
fit.i <- sarima( xdata = milk,
                 p = 0, d = 1, q = 0,
                 P = 1 , D = 1, Q = 1, S = 12,
                 details = F)
print('Coefficients')
```
```{r}
fit.i$fit$coef
```

```{r}
plot(fit.i$fit$residuals)
```

