---
title: "project"
author: "AO XU"
date: "2022-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tsdl) 
library(forecast) 
library(tidyverse) 
library(astsa)
library(MASS) 
library(ggplot2) 
library(readxl)
library(ggfortify) 
library(forecast) 
library(GeneCycle) 
library(qpcR) 
```
```{r}
length(tsdl[[203]])
attr(tsdl[[203]],"subject")
attr(tsdl[[203]],"source")
attr(tsdl[[203]],"description")
```

```{r}
milk <- tsdl[[203]]
plot.ts(milk)
str(milk)
```
```{r}
c_train <- ts(milk[1:156],start = c(1962,1),frequency = 12)
c_test <-ts(milk[157:168],start = c(1975,1),frequency = 12)
```
```{r}
bcTransform <- boxcox(c_train~as.numeric(1:length(c_train))) 
lambda = bcTransform$x[which(bcTransform$y == max(bcTransform$y))] 
milk.bc = (1/lambda)*(c_train^lambda-1)
lambda
```
$\lambda$ = 0 (log) and 1 are in the confidence interval, so we can choose either bc, log transforamtion or no transformation.

We choose box-cox transform for try.

```{r}
milk.bc <- (1/lambda)*(c_train^lambda-1)
plot.ts(milk.bc)
```

### Remove seasonality and trend
```{r}
# ln(Ut) differenced at lag 12
var(milk.bc)
milk.bc_12 <- diff(milk.bc, lag=12)
var(milk.bc_12)
# ln(Ut) differenced at lag 12 and then lag 1
milk.bc_12_1 <- diff(milk.bc_12, lag=1)
var(milk.bc_12_1)

```
Since 0.005246183 is the smallest number, so we choose to difference ln(Ut) at lag 12 and then 1 to approach the smallest variance.

```{r}
plot.ts(milk, main = "")

plot.ts(milk.bc_12, main = "bc(U_t) differenced at lag 12")
abline(h=mean(milk.bc_12), col = "blue")
fit <- lm(milk.bc_12 ~ as.numeric(1:length(milk.bc_12))) 


plot.ts(milk.bc_12_1, main = "bc(U_t) differenced at lag 12, at lag 1")
abline(h=mean(milk.bc_12_1), col = "blue")
fit2 <- lm(milk.bc_12_1 ~ as.numeric(1:length(milk.bc_12_1))) 
```
```{r}
acf(milk.bc_12_1, lag.max = 40, main =expression(nabla[1]~nabla[12]~~U[t]))
pacf(milk.bc_12_1, lag.max = 40, main = "")
```
```{r}
hist(milk.bc_12_1, density=20,breaks=20, col="blue", xlab="", prob=TRUE)
```
### Model Identification
```{r}
acf(milk.bc_12_1, lag.max = 120, main="ACF of the log(U_t)_12_1") 
pacf(milk.bc_12_1, lag.max = 120, main="ACF of the log(U_t)_12_1")
```

### Model Estimation


```{r}
a <- AICc(arima(milk.bc, order = c(0,1,1), seasonal = list(order = c(0,1,1), period = 12),method = "ML"))
a
```


```{r}
arima(milk.bc, order = c(0,1,1), seasonal = list(order = c(0,1,1), period = 12),method = "ML")
```




```{r}
polyroot(c(1, -2112))
```

```{r}
# Plot the residuals
fit1 <- arima(milk.bc, order = c(0,1,1),seasonal = list(order = c(0,1,1), period = 12), method = "ML")
res1 <- residuals(fit1)
par(mfrow=c(1,2))
hist(res1, density = 20, breaks = 20,
col = "blue", xlab = "", prob = TRUE, main = "") 
m1 <- mean(res1)
std1 <- sqrt(var(res1)) 
curve(dnorm(x,m1,std1),add = TRUE) 
qqnorm(res1,main = "", xlab = "") 
qqline(res1, col = "blue")
```
```{r}
shapiro.test(res1)
Box.test(res1,lag = 12, type = c("Box-Pierce"),fitdf = 3) # 3 coefficients
Box.test(res1,lag = 12, type = c("Ljung-Box"),fitdf = 3) # 3 coefficients
Box.test(res1^2,lag = 12, type = c("Ljung-Box"),fitdf = 0) 
ar(res1,aic=TRUE,order.max=NULL, method = c("yule-walker"))
```

### Spetral Analysis
```{r}
require(TSA)
# Graph the periodogram of Model 1 residual 
periodogram(res1)
abline(h = 0)
# Perform Kolmogorov-Smirnov Test on Model 1 residual
cpgram(res1, main = 'Kolmogorov-Smirnov Test') 
# Perform fisher test on Model 1 residual
fisher.g.test(res1)
```

```{r}
fit.1<-arima(c_train, order = c(0,1,1),
seasonal = list(order = c(0,1,1), period = 12), method = "ML")
pred.tr <- predict(fit.1, n.ahead = 12)
U = pred.tr$pred + 2*pred.tr$se
L = pred.tr$pred - 2*pred.tr$se
plot.ts(c_train, xlim = c(1962,1976), ylim = c(500,1000)) 
lines(U, col = "blue", lty = "dashed")
lines(L, col = "blue", lty = "dashed") 
points(pred.tr$pred,col = "red", pch = 1) 
```







